### ISSUE TITLE
Add documentation for new Promise support in dpd.js

### ISSUE THREAD

**Issue by dallonf** [deployd/docs#26]
Thanks to the community, we now have Promise support in Dpd.js! (https://github.com/deployd/deployd/pull/374)

This should be described in the documentation so that new users know that this option is available.

**Comment by NicolasRitouet** [comment]
Now that we also have promises for the internal dpd, we should also document this.

**Comment by NicolasRitouet** [comment]
I created a [new ticket](https://github.com/deployd/docs/issues/50) for the documentation of promises in the internal dpd
