### ISSUE TITLE
automatically generated apidocs from deployd resources 

### ISSUE THREAD

**Issue by coderofsalvation** [deployd/docs#71]
this would be very sweet..bit of documenation swag..
Oh wait..i just finished implementing a beta version ;) 

for anyone interested:

https://github.com/coderofsalvation/dpd-swagger-doc

**Comment by NicolasRitouet** [comment]
hey @coderofsalvation 

thx a lot for your plugin, it's indeed a very good idea, I'm personaly a big fan of swagger.
I'll close this ticket as it's not really an issue, but we should find a way to promote this great tools.
